### ISSUE TITLE
Checking your browser before accessing drivetest.ca.

### ISSUE THREAD

**Issue by Svision** [silverAndroid/drivetest-ca-availabilities#24]
CANNOT log in to the main booking page.
Checking your browser before accessing drivetest.ca. ALL THE TIME

**Comment by samiy803** [comment]
I think an easy solution would be to use puppeteer-extra and puppeteer-extra-plugin-stealth instead of just regular puppeteer.

**Comment by Svision** [comment]
> I think an easy solution would be to use puppeteer-extra and puppeteer-extra-plugin-stealth instead of just regular puppeteer.

How to do that exactly!

**Comment by silverAndroid** [comment]
@samiy803 I'll look into this

**Comment by jvchaitanya** [comment]
yes, it's going on with an infinite loop for captcha validation.

**Comment by silverAndroid** [comment]
@jvchaitanya Could you upload your log file, would help with determining what's going on

**Comment by jvchaitanya** [comment]
@silverAndroid  please find log given below.. 

```chaitanya@ip-192-168-0-14 drivetest-ca-availabilities % cat drivetest-2021-07-27_17-14-38.log 
{"level":30,"time":1627420478993,"pid":41974,"hostname":"chaitanyas.local","msg":"Checking for updates..."}
{"level":30,"time":1627420479638,"pid":41974,"hostname":"chaitanyas.local","msg":"No new updates found, current version 1.2.2"}
{"level":30,"time":1627420481783,"pid":41974,"hostname":"chaitanyas.local","msg":"Logging in..."}

**Comment by samiy803** [comment]
@silverAndroid here's an example with puppeteer-stealth. It's really crude and only gets past the login page. After that, it sends some GET requests.

https://github.com/samiy803/drive-test-example

**Comment by silverAndroid** [comment]
@samiy803 I took a preliminary look at puppeteer-stealth and [this issue](https://github.com/berstend/puppeteer-extra/issues/428#issuecomment-778679665) on puppeteer-extra worries me a bit since this project uses Typescript. I'll need to do some further investigation to see that downgrading Puppeteer doesn't affect any other code.

**Comment by ixpyro** [comment]
Not sure if this existed before, but there's a virtual queue to get into the booking system now.

**Comment by silverAndroid** [comment]
That's definitely new

**Comment by samiy803** [comment]
That virtual queue is broken. I booked an appointment, and my card got charged; instead of sending me to the confirmation page, it sent me back to the virtual queue. When I try calling them, and no one answers. I might give them a visit in person. 

I don't know why the government chooses Serco to manage the bookings, a kid in middle school can code a better system.

**Comment by Svision** [comment]
@samiy803 I usually try 10 times to call them to get one response. You might consider keeping trying to save yourself some time.
