### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by skalitin** [silverAndroid/drivetest-ca-availabilities#28]
**Describe the bug**
An "TypeError: Cannot read property 'url' of undefined" on attempt to parse bookingDateResponse. Stack trace and log output:

```
C:\Temp\drivetest-ca-availabilities>yarn start -m 3 -l 43.41164387982603,-79.73245219532673 -r 5 --chromiumPath "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
yarn run v1.22.11
$ node cli.js -m 3 -l 43.41164387982603,-79.73245219532673 -r 5 --chromiumPath "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
INFO (24668 on DESKTOP-CRQBOB1): Checking for updates...
INFO (24668 on DESKTOP-CRQBOB1): No new updates found, current version 1.3.1
INFO (24668 on DESKTOP-CRQBOB1): Please pass the HCaptcha to continue...
INFO (24668 on DESKTOP-CRQBOB1): Waiting to be allowed to leave waiting room...
INFO (24668 on DESKTOP-CRQBOB1): Logging in...
INFO (24668 on DESKTOP-CRQBOB1): Finding available times for a G exam
INFO (24668 on DESKTOP-CRQBOB1): Going to be searching these DriveTest centers: Oakville
INFO (24668 on DESKTOP-CRQBOB1): If you appreciate my work, feel free to buy me a ☕️ (coffee) here 😊: https://www.buymeacoffee.com/rushilperera
ERROR (24668 on DESKTOP-CRQBOB1): TypeError: Cannot read property 'url' of undefined
    at findAvailableDates_1 (C:\Temp\drivetest-ca-availabilities\scraper.js:203:64)
    at findAvailableDates_1.next (<anonymous>)
    at resume (C:\Temp\drivetest-ca-availabilities\scraper.js:36:44)
    at fulfill (C:\Temp\drivetest-ca-availabilities\scraper.js:38:31)
error Command failed with exit code 1.
```

**To Reproduce**
1. Start with the command line above and wait for some time in the waiting room
2. See error

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 92.0.902.67

**Comment by skalitin** [comment]
scraper.js:203:64 is this line:
```
            logger_1.logger.debug("waiting for response with dates for location");
            const bookingDateResponse = yield __await(responseListener_1.waitForResponse(page, responseListener_1.BOOKING_DATES_ID));
            month =
                **Number(new URLSearchParams(bookingDateResponse.url().split("?").pop()).get("month")) - 1;**
            const bookingDateJson = (yield __await(bookingDateResponse.json()));
            const { availableBookingDates, statusCode } = bookingDateJson;
            if (statusCode > 0) {

```

**Comment by skalitin** [comment]
Just noticed there is a log file too:
```
{"level":30,"time":1628704223338,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"Going to be searching these DriveTest centers: Oakville"}
{"level":20,"time":1628704223356,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"received response locations"}
{"level":20,"time":1628704223363,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"Attempt 1: calling selectLocation"}
{"level":20,"time":1628704223364,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"clicking a[id=\"9580\"]"}
{"level":20,"time":1628704223431,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"clicking #booking-location > div > div > form > div.form-group.loc-submit > div.directive_wrapper.ng-isolate-scope > button"}
{"level":20,"time":1628704223464,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"Called selectLocation successfully"}
{"level":20,"time":1628704223464,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"waiting for response with dates for location"}
{"level":10,"time":1628704228467,"pid":24668,"hostname":"DESKTOP-CRQBOB1","msg":"failed to wait for response"}

```

**Comment by tn133** [comment]
Hello, I got a similar error, except 'Cannot read property of json' instead of 'url'. Here is what happened after I was able to leave the waiting room:

`INFO (5740 on MacBook-Pro.local): Logging in...
INFO (5740 on MacBook-Pro.local): Finding available times for a G exam
INFO (5740 on MacBook-Pro.local): Going to be searching these DriveTest centers: Barrie, Clinton, Collingwood, Guelph, Guelph Temporary Testing Site, Kitchener, Orillia, Owen Sound, Parry Sound, Stratford, Walkerton
INFO (5740 on MacBook-Pro.local): Searching August at location Barrie
INFO (5740 on MacBook-Pro.local): Searching September at location Barrie
INFO (5740 on MacBook-Pro.local): Searching October at location Barrie
INFO (5740 on MacBook-Pro.local): Searching November at location Barrie
INFO (5740 on MacBook-Pro.local): Searching December at location Barrie
ERROR (5740 on MacBook-Pro.local): Attempt 1 to call selectLocation failed...waiting 1 second
INFO (5740 on MacBook-Pro.local): Searching August at location Clinton
INFO (5740 on MacBook-Pro.local): If you appreciate my work, feel free to buy me a ☕️ (coffee) here 😊: https://www.buymeacoffee.com/rushilperera
ERROR (5740 on MacBook-Pro.local): TypeError: Cannot read property 'json' of undefined
    at findAvailableDates_1 (/snapshot/drivetest-ca-availabilities/scraper.js)
    at findAvailableDates_1.next (<anonymous>)
    at resume (/snapshot/drivetest-ca-availabilities/scraper.js)
    at fulfill (/snapshot/drivetest-ca-availabilities/scraper.js)
`

**Comment by silverAndroid** [comment]
Will try and investigate this issue once the website decides to be a bit more cooperative 😂

**Comment by silverAndroid** [comment]
@skalitin @tn133 could you take a look at the new release I made and see if it fixes your issue?

**Comment by silverAndroid** [comment]
Closing as stale
