### ISSUE TITLE
Hang after click login button

### ISSUE THREAD

**Issue by kjstart** [silverAndroid/drivetest-ca-availabilities#30]
**Describe the bug**
Thanks for contributing to the open source world!

The login button keeps loading, and the page is stuck. Tried 3 times, same result.
System: osx 0.14.6
Browser: Chrome 92.0.4515.107
Command:
./drivetest-availabilities-macos -l * -r 80 -m 2 --licenseType G --email * --licenseNumber * --licenseExpiry * --chromiumPath /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

BTW, is your app go through each site once? Have you tried to repeat until session timeout? Do they ban bots users?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Comment by kjstart** [comment]
Chrome console:

Google Maps JavaScript API error: ClientBillingNotEnabledMapError
https://developers.google.com/maps/documentation/javascript/error-messages#client-billing-not-enabled-map-error

**Comment by silverAndroid** [comment]
When the login button is loading for a long time, it usually means the site is having trouble because it's under heavy load. 

To answer your other questions:
1. the script only goes through the site once to avoid situations like this where the site gets overloaded with users. 
1. It's something I'm debating currently on whether I should implement. 
1. I haven't seen any evidence of banning users but if the site detects you're a bot, they'll return a vague error message like "experiencing issues? Please call us" or something along those lines.

**Comment by silverAndroid** [comment]
However, since it's not an issue with the script, I'm closing this.

**Comment by kjstart** [comment]
Thank you for the kind responses.
Yes, the issue existing even I try it manually, seems stuck by sending emails.

Failed to load resource: the server responded with a status of 524 () /booking/v1/driver/email:1
